export const news = [
  {
    id: 1,
    title: "news 1",
    description: "news 1 description",
    tumble: "/images/slide (1).jpg",
  },
  {
    id: 2,
    title: "news 2",
    description: "news 2 description",
    tumble: "/images/slide (2).jpg",
  },
  {
    id: 3,
    title: "news 3",
    description: "news 3 description",
    tumble: "/images/slide (3).jpg",
  },
  {
    id: 4,
    title: "news 4",
    description: "news 4 description",
    tumble: "/images/slide (4).jpg",
  },
  {
    id: 5,
    title: "news 5",
    description: "news 5 description",
    tumble: "/images/slide (5).jpg",
  },
  {
    id: 6,
    title: "news 6",
    description: "news 6 description",
    tumble: "/images/slide (6).jpg",
  },
  {
    id: 1,
    title: "news 1",
    description: "news 1 description",
    tumble: "/images/slide (1).jpg",
  },
  {
    id: 2,
    title: "news 2",
    description: "news 2 description",
    tumble: "/images/slide (2).jpg",
  },
  {
    id: 3,
    title: "news 3",
    description: "news 3 description",
    tumble: "/images/slide (3).jpg",
  },
  {
    id: 4,
    title: "news 4",
    description: "news 4 description",
    tumble: "/images/slide (4).jpg",
  },
  {
    id: 5,
    title: "news 5",
    description: "news 5 description",
    tumble: "/images/slide (5).jpg",
  },
  {
    id: 6,
    title: "news 6",
    description: "news 6 description",
    tumble: "/images/slide (6).jpg",
  },
];

export const countries = [
  { name: "Afghanistan", flag: "https://flagcdn.com/w320/af.png" },
  { name: "Albania", flag: "https://flagcdn.com/w320/al.png" },
  { name: "Algeria", flag: "https://flagcdn.com/w320/dz.png" },
  { name: "Andorra", flag: "https://flagcdn.com/w320/ad.png" },
  { name: "Angola", flag: "https://flagcdn.com/w320/ao.png" },
  { name: "Argentina", flag: "https://flagcdn.com/w320/ar.png" },
  { name: "Armenia", flag: "https://flagcdn.com/w320/am.png" },
  { name: "Australia", flag: "https://flagcdn.com/w320/au.png" },
  { name: "Austria", flag: "https://flagcdn.com/w320/at.png" },
  { name: "Azerbaijan", flag: "https://flagcdn.com/w320/az.png" },
  { name: "Bahamas", flag: "https://flagcdn.com/w320/bs.png" },
  { name: "Bahrain", flag: "https://flagcdn.com/w320/bh.png" },
  { name: "Bangladesh", flag: "https://flagcdn.com/w320/bd.png" },
  { name: "Barbados", flag: "https://flagcdn.com/w320/bb.png" },
  { name: "Belarus", flag: "https://flagcdn.com/w320/by.png" },
  { name: "Belgium", flag: "https://flagcdn.com/w320/be.png" },
  { name: "Belize", flag: "https://flagcdn.com/w320/bz.png" },
  { name: "Benin", flag: "https://flagcdn.com/w320/bj.png" },
  { name: "Bhutan", flag: "https://flagcdn.com/w320/bt.png" },
  { name: "Bolivia", flag: "https://flagcdn.com/w320/bo.png" },
  { name: "Bosnia and Herzegovina", flag: "https://flagcdn.com/w320/ba.png" },
  { name: "Botswana", flag: "https://flagcdn.com/w320/bw.png" },
  { name: "Brazil", flag: "https://flagcdn.com/w320/br.png" },
  { name: "Brunei", flag: "https://flagcdn.com/w320/bn.png" },
  { name: "Bulgaria", flag: "https://flagcdn.com/w320/bg.png" },
  { name: "Burkina Faso", flag: "https://flagcdn.com/w320/bf.png" },
  { name: "Burundi", flag: "https://flagcdn.com/w320/bi.png" },
  { name: "Cambodia", flag: "https://flagcdn.com/w320/kh.png" },
  { name: "Cameroon", flag: "https://flagcdn.com/w320/cm.png" },
  { name: "Canada", flag: "https://flagcdn.com/w320/ca.png" },
  { name: "Cape Verde", flag: "https://flagcdn.com/w320/cv.png" },
  { name: "Central African Republic", flag: "https://flagcdn.com/w320/cf.png" },
  { name: "Chad", flag: "https://flagcdn.com/w320/td.png" },
  { name: "Chile", flag: "https://flagcdn.com/w320/cl.png" },
  { name: "China", flag: "https://flagcdn.com/w320/cn.png" },
  { name: "Colombia", flag: "https://flagcdn.com/w320/co.png" },
  { name: "Comoros", flag: "https://flagcdn.com/w320/km.png" },
  { name: "Congo", flag: "https://flagcdn.com/w320/cg.png" },
  { name: "Costa Rica", flag: "https://flagcdn.com/w320/cr.png" },
];

export const episodes = [
  {
    id: 0,
    imgUrl: "/images/slide (1).jpg",
    message: "Tra flog",
  },
  {
    id: 1,
    imgUrl: "/images/slide (2).jpg",
    message: "Tra flog",
  },
  {
    id: 2,
    imgUrl: "/images/slide (3).jpg",
    message: "Tra flog",
  },
  {
    id: 3,
    imgUrl: "/images/slide (4).jpg",
    message: "Tra flog",
  },
  {
    id: 4,
    imgUrl: "/images/slide (5).jpg",
    message: "Tra flog",
  },
  {
    id: 5,
    imgUrl: "/images/slide (6).jpg",
    message: "Tra flog",
  },
  {
    id: 0,
    imgUrl: "/images/slide (1).jpg",
    message: "Tra flog",
  },
  {
    id: 1,
    imgUrl: "/images/slide (2).jpg",
    message: "Tra flog",
  },
  {
    id: 2,
    imgUrl: "/images/slide (3).jpg",
    message: "Tra flog",
  },
  {
    id: 3,
    imgUrl: "/images/slide (4).jpg",
    message: "Tra flog",
  },
  {
    id: 4,
    imgUrl: "/images/slide (5).jpg",
    message: "Tra flog",
  },
  {
    id: 5,
    imgUrl: "/images/slide (6).jpg",
    message: "Tra flog",
  },
  {
    id: 0,
    imgUrl: "/images/slide (1).jpg",
    message: "Tra flog",
  },
  {
    id: 1,
    imgUrl: "/images/slide (2).jpg",
    message: "Tra flog",
  },
  {
    id: 2,
    imgUrl: "/images/slide (3).jpg",
    message: "Tra flog",
  },
  {
    id: 3,
    imgUrl: "/images/slide (4).jpg",
    message: "Tra flog",
  },
  {
    id: 4,
    imgUrl: "/images/slide (5).jpg",
    message: "Tra flog",
  },
  {
    id: 5,
    imgUrl: "/images/slide (6).jpg",
    message: "Tra flog",
  },
  {
    id: 0,
    imgUrl: "/images/slide (1).jpg",
    message: "Tra flog",
  },
  {
    id: 1,
    imgUrl: "/images/slide (2).jpg",
    message: "Tra flog",
  },
  {
    id: 2,
    imgUrl: "/images/slide (3).jpg",
    message: "Tra flog",
  },
  {
    id: 3,
    imgUrl: "/images/slide (4).jpg",
    message: "Tra flog",
  },
  {
    id: 4,
    imgUrl: "/images/slide (5).jpg",
    message: "Tra flog",
  },
  {
    id: 5,
    imgUrl: "/images/slide (6).jpg",
    message: "Tra flog",
  },
  {
    id: 0,
    imgUrl: "/images/slide (1).jpg",
    message: "Tra flog",
  },
  {
    id: 1,
    imgUrl: "/images/slide (2).jpg",
    message: "Tra flog",
  },
  {
    id: 2,
    imgUrl: "/images/slide (3).jpg",
    message: "Tra flog",
  },
  {
    id: 3,
    imgUrl: "/images/slide (4).jpg",
    message: "Tra flog",
  },
  {
    id: 4,
    imgUrl: "/images/slide (5).jpg",
    message: "Tra flog",
  },
  {
    id: 5,
    imgUrl: "/images/slide (6).jpg",
    message: "Tra flog",
  },
];
